apiVersion: v1
kind: Service
metadata:
  name: geometric-shapes-service
  labels:
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: geometric-shapes-app
    tier: backend
  ports:
    - port: 9000
      targetPort: 9000
