apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  loadBalancerIP: 127.0.0.1
  selector:
    app: nginx
    tier: backend
  ports:
    - port: 80
      targetPort: 80
